# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    sources: 
      - ./*.go
      - ./main/main.go
    generates:
      - dist/awclip    
    cmds:
      - go build -o dist/awclip main/main.go
      - cp dist/awclip ~/Documents/eprojects/prowler  

# silent: true
