// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package services

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/iam"
	"sync"
)

// Ensure, that IamInterfaceMock does implement IamInterface.
// If this is not the case, regenerate this file with moq.
var _ IamInterface = &IamInterfaceMock{}

// IamInterfaceMock is a mock implementation of IamInterface.
//
//     func TestSomethingThatUsesIamInterface(t *testing.T) {
//
//         // make and configure a mocked IamInterface
//         mockedIamInterface := &IamInterfaceMock{
//             ListUserPoliciesFunc: func(ctx context.Context, params *iam.ListUserPoliciesInput, optFns ...func(*iam.Options)) (*iam.ListUserPoliciesOutput, error) {
// 	               panic("mock out the ListUserPolicies method")
//             },
//         }
//
//         // use mockedIamInterface in code that requires IamInterface
//         // and then make assertions.
//
//     }
type IamInterfaceMock struct {
	// ListUserPoliciesFunc mocks the ListUserPolicies method.
	ListUserPoliciesFunc func(ctx context.Context, params *iam.ListUserPoliciesInput, optFns ...func(*iam.Options)) (*iam.ListUserPoliciesOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListUserPolicies holds details about calls to the ListUserPolicies method.
		ListUserPolicies []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *iam.ListUserPoliciesInput
			// OptFns is the optFns argument value.
			OptFns []func(*iam.Options)
		}
	}
	lockListUserPolicies sync.RWMutex
}

// ListUserPolicies calls ListUserPoliciesFunc.
func (mock *IamInterfaceMock) ListUserPolicies(ctx context.Context, params *iam.ListUserPoliciesInput, optFns ...func(*iam.Options)) (*iam.ListUserPoliciesOutput, error) {
	if mock.ListUserPoliciesFunc == nil {
		panic("IamInterfaceMock.ListUserPoliciesFunc: method is nil but IamInterface.ListUserPolicies was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *iam.ListUserPoliciesInput
		OptFns []func(*iam.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockListUserPolicies.Lock()
	mock.calls.ListUserPolicies = append(mock.calls.ListUserPolicies, callInfo)
	mock.lockListUserPolicies.Unlock()
	return mock.ListUserPoliciesFunc(ctx, params, optFns...)
}

// ListUserPoliciesCalls gets all the calls that were made to ListUserPolicies.
// Check the length with:
//     len(mockedIamInterface.ListUserPoliciesCalls())
func (mock *IamInterfaceMock) ListUserPoliciesCalls() []struct {
	Ctx    context.Context
	Params *iam.ListUserPoliciesInput
	OptFns []func(*iam.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *iam.ListUserPoliciesInput
		OptFns []func(*iam.Options)
	}
	mock.lockListUserPolicies.RLock()
	calls = mock.calls.ListUserPolicies
	mock.lockListUserPolicies.RUnlock()
	return calls
}
